.TH VideoToAscii 1 "March 2025" "Version1.0" "User commands"
.SH NAME
imageToAscii \- Converts an image into ASCII art.
.SH SYNOPSIS
.B imageToAscii
[\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
ImageToAscii is a tool that process pictures into frames using OpenCV and represents it into the terminal as ASCII Art.
.SH OPTIONS
.TP
.B \-p \fINUMBER\fR, \-\-pattern \fINUMBER\fR
Select an ASCII pattern .In case of invalid number the default pattern is used instead (0).
.RS
 0 "@%#*+=-:. "
 1 " .:-=+*#%@"
 2  "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/|()1{}[]?-_+~<>i!lI;:,^`'."
 3  " .'`^,:;Il!i><~+_-?][}{1)(|/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$"
 4 "@%#*+=-:.                                  '"
 5 "'                                 .:-=+*#%@!"
 6 ".',-^_~()[]{}<>|/\\"
 7 "\\/|><}{}][)(~_^-,'.)]"
 8 "ZYXWVUTSRQPONMLKJIHGFEDCBA"
 9 "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
 10 "@B8&$%#*+=-:. ,"
 11 ", .:-=+*#%$&8B@"

.B \-f \fIFILE\fR, \-\-file \fIFILE\fR
Specify a custom source file to process.If non provided the default is used instead
which is located at sample/sample.jpg
.TP
.B \-s, \-\-sobel
Apply the Sobel operator to enchance edges before converting the frame to ASCII
.TP
.B \-S, \-\-Sharpen
Applies Sharpening to each frame that is getting converted to ASCII
.TP
.B \-g, \-\-Gaussian
Applies Gaussian blur to each frame that is getting converted to ASCII
.TP
.B \-C, \-\-Color
Applies Colors to the ascii characters,although it overrides the other filters
